import IconMorningNew from 'images/sprite/morning-new.svg';
import IconDaytimeNew from 'images/sprite/daytime-new.svg';
import IconEveningNew from 'images/sprite/evening-new.svg';
import IconMorningWhite from 'images/sprite/morning-white.svg';
import IconDaytimeWhite from 'images/sprite/daytime-white.svg';
import IconEveningWhite from 'images/sprite/evening-white.svg';

import IconVapeNew from 'images/sprite/vape-new.svg';
import IconJointNew from 'images/sprite/joint-new.svg';
import IconBongNew from 'images/sprite/bong-new.svg';
import IconEdiblesNew from 'images/sprite/edibles-new.svg';
import IconVapeWhite from 'images/sprite/vape-white.svg';
import IconJointWhite from 'images/sprite/joint-white.svg';
import IconBongWhite from 'images/sprite/bong-white.svg';
import IconEdiblesWhite from 'images/sprite/edibles-white.svg';

const POSITIVE_EFFECTS_OPTIONS = [
  'Relaxed',
  'Happy',
  'Uplifted',
  'Appetite Enhancing',
  'Euphoric',
  'Calming',
  'Energetic',
  'Creative',
  'Focused',
  'Sleepy',
  'Awake',
  'Motivated',
  'Tasteful',
  'Giggly',
  'Social',
  'None',
];

const NEGATIVE_EFFECTS_OPTIONS = [
  'Dry Mouth',
  'Dry Eyes',
  'Coughing',
  'Sleepy',
  'Hungry',
  'Red Eyes',
  'Talkative',
  'Dizzy',
  'Headache',
  'Anxiety',
  'Giggly',
  'Harsh',
  'Lazy',
  'Paranoia',
  'Chest Congestion',
  'Nausea',
  'Insomnia',
  'Bad Taste',
  'Forgetful',
  'Smell',
  'Irritability',
  'Weak',
  'Cough',
  'Short High',
  'Restless',
  'None',
];

const SYMPTOMS_HELPED_OPTIONS = [
  'Anxiety',
  'Stress',
  'Pain',
  'Depression',
  'Insomnia',
  'Inflammation',
  'Lack Of Appetite',
  'Fatigue',
  'Back Pain',
  'Headaches',
  'Nausea',
  'Muscle Spasms',
  'Mood',
  'Cramps',
  'Arthritis',
  'Concentration',
  'Add/Adhd',
  'Muscle Pain',
  'Social Anxiety',
  'Ptsd',
  'Fibromyalgia',
  'Eye Pressure',
  'Neck Pain',
  'Nerve Pain',
  'Panic Attacks',
  'Irritable Bowel Syndrome',
  'Seizures',
  'Joint Pain',
  'Obsessive Compulsive Disorder',
  'Stomach Pain',
  'Appetite',
  'None',
];

const CONSUMPTION_METHODS_OPTIONS = [
  {
    title: 'Vaporizer',
    value: 'vaporizer',
    icon: IconVapeNew,
    activeIcon: IconVapeWhite,
  },
  {
    title: 'Joint',
    value: 'joint',
    icon: IconJointNew,
    activeIcon: IconJointWhite,
  },
  {
    title: 'Bong',
    value: 'bong',
    icon: IconBongNew,
    activeIcon: IconBongWhite,
  },
  {
    title: 'Edibles',
    value: 'edibles',
    icon: IconEdiblesNew,
    activeIcon: IconEdiblesWhite,
  },
];

const TIME_OF_CONSUMPTION_OPTIONS = [
  {
    title: 'Morning',
    value: 'morning',
    icon: IconMorningNew,
    activeIcon: IconMorningWhite,
  },
  {
    title: 'Daytime',
    value: 'daytime',
    icon: IconDaytimeNew,
    activeIcon: IconDaytimeWhite,
  },
  {
    title: 'Evening',
    value: 'evening',
    icon: IconEveningNew,
    activeIcon: IconEveningWhite,
  },
];

const FLAVOUR_OPTIONS = [
  'earthy',
  'sweet',
  'pungent',
  'citrus',
  'woody',
  'fruity',
  'pine',
  'lemon',
  'flowery',
  'spicy/herbal',
  'skunk',
  'spicy',
  'musk',
  'diesel',
  'berry',
  'sour',
  'tropical',
  'cheese',
  'blueberry',
  'nutty',
  'lime',
  'chemical',
  'grape',
  'sage',
  'grapefruit',
  'orange',
  'vanilla',
  'mango',
  'honey',
  'minty',
  'coffee',
  'butter',
  'pineapple',
  'juniper',
  'chestnut',
  'menthol',
  'fresh chives',
  'wild garlic',
  'cherry',
  'lavender',
  'fruit',
  'skunky',
  'floral',
  'piney',
  'kush',
  'ammonia',
  'earth',
  'pepper',
  'mild',
  'herbal',
  'bitter',
  'musky',
  'smooth',
  'hops',
  'garlic',
  'spice',
  'wood',
  'citrusy',
  'peppery',
  'dank',
  'banana',
];

const PRESCRIBED_FOR_OPTIONS = [
  'anxiety',
  'pain',
  'stress',
  'depression',
  'insomnia',
  'migraines',
  'arthritis',
  'ptsd',
  'add/adhd',
  'nausea',
  'gastrointestinal disorder',
  'fibromyalgia',
  'spinal cord injury',
  'asthma',
  'pms',
  'bipolar disorder',
  'hypertension',
  'crohns disease',
  'multiple sclerosis',
  'cancer',
  'colitis',
  'epilepsy',
  'chronic pain',
  'anorexia',
  'rather not say',
  'glaucoma',
  'ibs',
  'endometriosis',
  'lupus',
  'adhd',
  'ocd',
  'tourettes syndrome',
  'back pain',
  'sciatica',
  'social anxiety',
  'irritable bowel syndrome',
  'nerve pain',
  'scoliosis',
  'ddd',
  'degenerative disc disease',
  'muscular dystrophy',
  'diabetes',
  'bpd',
  'sleep issues',
  'phantom limb pain',
  'borderline personality disorder',
  'muscle spasms',
  'lack of appetite',
  'sleep apnea',
  'eating disorder',
  'psoriasis',
  'osteoarthritis',
  'asd',
  'parkinsons',
  'nerve damage',
  'migraine',
  'trouble sleeping',
  'ehlers danlos syndrome',
  'headaches',
  'fatigue',
  'crohns',
  'crps',
  'add',
  'sciatic nerve',
  'chronic pancreatitis',
  'narcolepsy',
  'brain injury',
  'ibs/ibd',
  'chronic back pain',
  'tmj',
  'joint pain',
  'gout',
  'lower back pain',
  'head trauma',
  'spinal stenosis',
  'neuropathy',
  'panic disorder',
  'inflammation',
  'restless leg syndrome',
  'neck pain',
  'eds',
  'panic attacks',
  'ibd',
  'loss of appetite',
  'cataplexy',
  'pots',
  'muscle pain',
  'disordered eating',
  'crohns disease',
  'sleep disorder',
  'spasms',
  'postural orthostatic tachycardia syndrome',
  'psoriatic arthritis',
  'sjogrens syndrome',
  'cachexia',
  'fibro',
  'muscle and nerve pain',
  'trauma',
  'generalized anxiety disorder',
  'bipolar',
  'complex regional pain syndrome',
  'stomach pain',
  'rheumatoid arthritis',
  'obsessive compulsive disorder',
  'severe ocd and acute anxiety hoarding',
  'seizures',
  'trigeminal neuralgia',
  'diabetic nephropathy',
  'disordered sleep',
  'hyperemesis gravidarum',
  'dystonia',
  'liver disease',
  'life',
  'bi-polar',
  'muscle stiffness',
  'eczema',
  'bursitis',
  'lyme disease',
  'cllpss',
  'gad',
  'appetite loss',
  'alzheimers',
  'ednos',
  'gastroparesis',
  'high-voltage electrical burns',
  'amputations',
  'pelvic prolapse',
  'pcos',
];

const EXPERIENCE_WITH_CANNABIS = [
  {
    label: 'New',
    value: 'new',
  },
  {
    label: 'Familiar',
    value: 'familiar',
  },
  {
    label: 'Connoisseur',
    value: 'connoisseur',
  },
];

const GENDER_OPTIONS = [
  {
    label: 'Male',
    value: 'male',
  },
  {
    label: 'Female',
    value: 'female',
  },
  {
    label: 'Other',
    value: 'other',
  },
];

export default {
  POSITIVE_EFFECTS_OPTIONS,
  NEGATIVE_EFFECTS_OPTIONS,
  SYMPTOMS_HELPED_OPTIONS,
  CONSUMPTION_METHODS_OPTIONS,
  TIME_OF_CONSUMPTION_OPTIONS,
  FLAVOUR_OPTIONS,
  PRESCRIBED_FOR_OPTIONS,
  EXPERIENCE_WITH_CANNABIS,
  GENDER_OPTIONS,
};
