const terms = {
  title: 'Lift.co and Lift Rewards™',
  liftRewardsToS: `<div>
    <p style="text-align: center;"><strong>GENERAL TERMS OF USE</strong></p>
    <p>PLEASE READ THESE TERMS OF USE CAREFULLY AS THEY CONTAIN IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES AND OBLIGATIONS. THESE INCLUDE VARIOUS LIABILITY LIMITATIONS AND EXCLUSIONS, AND A DISPUTE RESOLUTION CLAUSE THAT GOVERNS HOW DISPUTES WILL BE RESOLVED.</p>
    <p style="text-align: center;"><strong><u>USE AT YOUR OWN RISK.</u></strong></p>
    <p>Access and use of this website (the "Site") and its related services (the "Services") are provided by Lift Co. Ltd. ("Lift", "we" and "us") to you on condition that you accept these Terms of Use, and by accessing or using this Site or the Services, you agree to these Terms of Use. If you do not agree to accept and abide by these Terms of Use you may not access or use this Site or the Services.</p>
    <p>These Terms of Use govern the relationship between you, the Site visitor and/or member (“you”), and Lift with respect to your use of the this Site and its related Services. You agree that the agreement formed by these Terms of Use is like any written negotiated agreement signed by you, and you agree to be bound by, and fully comply with, its terms. You represent and warrant that you have all necessary right, power and authority to enter into this agreement and to perform and otherwise discharge all of your obligations hereunder.</p>
    <p>THE PURPOSE OF THE SITE AND SERVICES ARE TO ENABLE YOU TO PURCHASE PRODUCTS AND ACCESSORIES MANUFACTURED BY THIRD PARTIES. LIFT IS NOT RESPONSIBLE FOR: (I) THE ACCURACY OR RELIABILITY OF ANY MEDICAL OPINION, ADVICE, TESTIMONIAL OR STATEMENT MADE ON THE SITE (INCLUDING, WITHOUT LIMITATION, ANY INFORMATION OR REVIEWS POSTED BY OTHER USERS); (II) ANY INFORMATION POSTED ON THE SITE; OR (III) ANY MENTAL OR BODILY INJURY, INCLUDING LOSS OF LIFE OR LOSS OF BODILY FUNCTIONS, SUSTAINED BY YOU IN CONNECTION WITH YOUR USE OF THE SITE OR THE SERVICES, INCLUDING WITHOUT LIMITATION DUE TO ANY PRODUCTS OR ACCESSORIES PURCHASED BY YOU THROUGH THE SITE OR SERVICES. THE FOREGOING DISCLAIMER AND LIMITATIONS OF LIABILITY SHALL NOT LIMIT THE DISCLAIMERS AND LIMITATIONS OF LIABILITY SET OUT IN SECTIONS 13 AND 14.</p>
    <p>ALL INFORMATION CONTAINED ON THE SITE IS FOR INFORMATIONAL PURPOSES ONLY AND IS NOT MEANT TO BE A SUBSTITUTE FOR THE ADVICE PROVIDED BY YOUR OWN DOCTOR. UNDER NO CIRCUMSTANCES SHOULD ANY SUCH INFORMATION BE USED FOR THE DIAGNOSIS OR TREATMENT OF ANY MEDICAL CONDITION.</p>
    <h4>1. JURISDICTION</h4>
    <p>You understand that aspects of this Site and the Services may not be available in all jurisdictions and that you are responsible for ensuring that it is lawful for you to use this Site and receive the Services where these activities occur.</p>
    <p>If you reside in a jurisdiction which restricts the use of Internet-based applications according to age, or which restricts the ability to enter into agreements such as set out in these Terms of Use according to age and you are under such a jurisdiction and under such age limit, you may not enter into this agreement or use this Site or the Services. Minors are not permitted to use the Site or Services.</p>
    <p>If you reside in a jurisdiction which restricts the use of Internet-based applications according to age, or which restricts the ability to enter into agreements such as set out in these Terms of Use according to age and you are under such a jurisdiction and under such age limit, you may not enter into this agreement or use this Site or the Services. <u>Minors are not permitted to use the Site or Services.</u></p>
    <p> Furthermore, if you reside in a jurisdiction where it is forbidden by law to participate in the activities offered by this Site or the Services, or to purchase or possess any or all of the products or accessories for sale on the Site, you may not enter into this agreement or use this Site or the Services. By using this Site you are explicitly representing that you have verified that your use of this Site and the Services and purchase and possession of products and accessories available for sale on the Site is allowed in your own jurisdiction. </p>
    <p> Your Account (as defined below) may be deleted and these Terms of Use may be suspended or terminated without warning, if we believe that you are under age or your use of this Site or the Services is not allowed (among other reasons set out below). </p>
    <h4> 2. PRIVACY </h4>
    <p> Lift is committed to respecting the privacy of the personal information of the individuals with whom we interact. We have developed a Privacy Policy (https://lift.co/privacy) to describe our privacy policies and practices and how we collect, use and disclose the personal information of those individuals who visit this Site or use the Services. Please see our Privacy Policy (https://lift.co/privacy) for further details and contact information for our Privacy Officer. </p>
    <p> You acknowledge and agree that access to and use of this Site and the Services is provided via the Internet and that your information, including personal information, may be transferred across national borders and stored or processed in any country in the world. </p>
    <h4> 3. ACCOUNTS </h4>
    <p> In order to access and use certain of the Services available on this Site, you may need to sign up for, open and maintain an account (“Account”). Prior to completing the signup process for your Account, you will be required to indicate your acceptance of all of the terms and conditions of these Terms of Use. If you do not agree to these Terms of Use, you may not sign up for an Account. </p>
    <p> During the registration process we may collect your name, address, email address, phone number, credit card information, username, and password. Your information may be used by us in connection with the Services or your use of the Site: </p>
    <p> * to verify your eligibility to create and to maintain your Account; </p>
    <p> * to ensure that your Account, including your username, is unique; </p>
    <p> * to enable us to provide certain security and privacy safeguards; </p>
    <p> * to deal with security, debugging and technical support issues; </p>
    <p> * for billing and payment-related issues; </p>
    <p> * to protect ourselves and others from abuse; </p>
    <p> * to conduct a criminal or other background check in relation to you; and </p>
    <p> * to comply with law. </p>
    <p> All of the information you provide to us or that we collect from you in connection with your use of the Site or the Services will be governed by these Terms of Use. You agree at all times to: (i) provide accurate, current and complete information about yourself as prompted by our registration form or otherwise; and (ii) maintain and update your information (including your e-mail address) to keep it accurate, current and complete. You acknowledge that, if any information provided by you is untrue, inaccurate, not current or incomplete, we may suspend or terminate your Account and your ability to use this Site or the Services and, in our sole discretion, to report you to appropriate authorities. </p>
    <p> We hereby disclaim any and all responsibility or liability for any unauthorized use of your Account. </p>
    <p> You must not choose a username that infringes the rights of any third party, impersonates any Lift employee, other user, celebrity or any famous person or entity, which is deliberately confusing or which is offensive, racist, obscene, hurtful, unlawful or otherwise inappropriate. You agree that you will not use misspellings or alternative spellings or take any other actions for the purpose of circumventing the foregoing restrictions. You understand and agree that, in addition to the foregoing restrictions, we reserve the right to change, remove, alter or delete any username at any time and for any reason in our sole discretion. </p>
    <p> YOU ARE ENTIRELY RESPONSIBLE FOR MAINTAINING THE CONFIDENTIALITY OF YOUR USERNAME AND PASSWORD AND FOR ANY AND ALL ACTIVITIES (INCLUDING PURCHASES AND CHARGES, AS APPLICABLE) THAT ARE CONDUCTED THROUGH YOUR ACCOUNT. </p>
    <p> You cannot transfer your Account to any other person, or permit anyone to use it. </p>
    <p> You agree to notify us immediately of any unauthorized use, theft or misappropriation of your account, username, or password. We shall not be liable for any loss that you incur as a result of someone else using your username or password, either with or without your knowledge. </p>
    <h4> 4. PERSONAL USE ONLY </h4>
    <p> This Site and the Services are only for personal use. You may not use this Site or the Services for commercial purposes, including without limitation to resell any products or accessories purchased through the Site or using the Services, or in any way that is unlawful, or harms us or any other person or entity, as determined in our sole discretion. </p>
    <h4> 5. CODE OF CONDUCT </h4>
    <p> You may not interfere with the security of, or otherwise abuse this Site, the Services or any system resources, services or networks connected to or accessible through this Site or the Services. You may only use this Site and the Services for lawful purposes. You agree that you will not attempt to, nor permit any third party to, enter restricted areas of Lift's computer systems or perform functions that you are not authorized to perform. </p>
    <p> Lift may, without notice, temporarily suspend your, or any other party's, access to this Site or the Services by deactivating any Account, password(s) or links to the Internet if we reasonably suspect that you, or any other parties, are obtaining unauthorized access to our other systems or information, or are using otherwise valid user identifications or passwords in any unauthorized manner. These suspensions will be for such periods of time as Lift may reasonably determine is necessary to permit the thorough investigation and mitigation of such suspended activity. </p>
    <p> While using this Site or the Services you agree to comply with all applicable laws, rules and regulations, including without limitation any laws governing the transmission of commercial electronic messages or similar. We reserve the right, in our sole discretion, to take any actions we deem necessary and appropriate to preserve the integrity of this Site and the Services. </p>
    <p> You agree not to post anything on the Site that: </p> <p> * is defamatory, abusive, harassing, threatening, or an invasion of a right of privacy of another person; </p>
    <p> * is bigoted, hateful, or racially or otherwise offensive; </p>
    <p> * is violent, vulgar, obscene, pornographic or otherwise sexually explicit, or otherwise harms or can reasonably be expected to harm any person or entity; </p>
    <p> * is misleading, untruthful or inaccurate; </p>
    <p> * is illegal or encourages or advocates illegal activity or the discussion of illegal activities with the intent to commit them, including without limitation a submission that is, or represents an attempt to engage in, child pornography, stalking, sexual assault, fraud, trafficking in obscene or stolen material, drug dealing and/or drug abuse, harassment, theft, or conspiracy to commit any criminal activity; or </p>
    <p> * infringes or violates any right of a third party including: (i) copyright, patent, trademark, trade secret or other proprietary or contractual rights; (ii) rights of privacy (specifically, you must not distribute another person's personal information of any kind without their express permission) personality or publicity; or (iii) any confidentiality obligation. </p>
    <p> You acknowledge that Lift may remove, delete or edit any post, information or content provided by you for any reason whatsoever, including non-compliance with the foregoing. </p>
    <h4> 6. AVAILABILITY </h4>
    <p> While we endeavour to keep downtime to a minimum, we can't promise that this Site or the Services will be uninterrupted, secure or error-free. We reserve the right to interrupt or suspend this Site or the Services, or any part thereof, with or without prior notice for any reason. </p>
    <h4> 7. ACCESS TO THE INTERNET </h4>
    <p> You are solely responsible for obtaining and maintaining all Internet, computer hardware and other equipment needed to access and use this Site and the Services and that you shall be solely responsible for all charges and fee related thereto. </p>
    <h4> 8. CHANGES TO SITE AND CONTENT </h4>
    <p> Lift may revise, supplement or delete information, services and/or the resources contained in this Site and the Services and reserves the right to make such changes without prior notification to past, current or prospective visitors. For the avoidance of doubt, we reserve the right at any time to change: (i) the terms and conditions of these Terms of Use; (ii) this Site or the Services, including terminating, eliminating, supplementing, modifying, adding or discontinuing any content or feature or data or service on or available through this Site or the Services or the hours that they are available; (iii) any fees or charges, if any, related to the use of this Site or the Services or the purchase of products; and (iv) the equipment, hardware or software required to use and access this Site or the Services. </p>
    <p> Any changes we make to these Terms of Use will be effective immediately upon notice, which we may provide by any means including, without limitation, posting on this website. Your continued use of this Site or the Services after such notice will be deemed acceptance of such changes. Be sure to return to this Site periodically to ensure you are familiar with the most current version of these Terms of Use. </p>
    <h4> 9. LINKED WEBSITES </h4>
    <p> This Site or the Services may provide links to third party websites for your convenience only. The inclusion of these links does not imply that Lift monitors or endorses these websites. Lift does not accept any responsibility for such websites. Lift shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or the reliance upon any information, content, goods or services available on or through any third party websites or linked resources. </p>
    <h4> 10. INTERNET SOFTWARE OR COMPUTER VIRUSES </h4>
    <p> Lift shall not be responsible or liable for any software, computer viruses or other destructive, harmful or disruptive files or programs that may infect or otherwise impact your use of your computer equipment or other property on account of your access to, use of, or browsing on this Site or the Services or other content from this Site. Lift suggests that you take prudent action to protect yourself, such as installing appropriate anti-virus or other protective software. </p>
    <h4> 11. PAYMENTS, SHIPPING, CUSTOMER SERVICE, REFUNDS </h4>
    <p> If you wish to purchase products or accessories through your Account, you must provide us with a valid Visa®, MasterCard® or American Express® card number, or PayPal account. By submitting this information to us, you give Lift permission to charge your order to the card or account that you designate. You agree that, under no circumstances, including without limitation Account termination or suspension, will Lift provide you with any refund of any amount paid. Unless otherwise agreed to at the time of account creation, Lift will bill you in monthly installments for any Account fees. </p>
    <p> Under no circumstances will we be responsible: (i) for any charges that your credit card issuer may apply to you as a result of our processing your order; (ii) if your card issuer refuses or fails to authorize payment by you; or (iii) for any delays or non-delivery of the item that you endeavoured to purchase arising from any validation checks that may be carried out regarding your payment or identification. </p>
    <p> 2360149 Ontario Inc. ("180 Smoke") provides shipping, product warranty and customer service in relation to any products or accessories available for sale through the Site and Services. 180 Smoke imposes its own terms and conditions in relation to shipping, product warranty, customer service and returns / refunds / exchanges. By making a purchase through the Site or Services, you agree that the terms and conditions of 180 Smoke, which can be found at (https://www.180smoke.ca/terms-conditions), will govern all matters related to shipping, product warranty, customer service and returns / refunds / exchanges, and that you will be bound to those terms and conditions. You further agree that, as between you and Lift, Lift shall have no obligations or liabilities to you with respect to any of these matters. </p>
    <h4> 12. INTELLECTUAL PROPERTY </h4>
    <p> This Site and the Services are owned and operated by Lift and may be protected by intellectual property laws including laws relating to copyrights, trade-marks, trade-names, Internet domain names, notice and notice rights, and other similar rights under the laws of Ontario, Canada. </p>
    <p> To the extent that you use the Site or the Services to post, display or otherwise make available text, images, video recordings, audio recordings, or any other information capable of protection by intellectual property laws or other exclusive rights, you agree to grant, and hereby grant, Lift a perpetual, non-exclusive, royalty-free, worldwide license to reproduce, display, alter, or otherwise make available such works. Further, you agree to waive, and hereby waive, any moral rights, personality rights, publicity rights and similar that you may have in same. </p>
    <p> SITE AND SERVICES PROVIDED “AS IS” THIS SITE (INCLUDING, WITHOUT LIMITATION, THE INFORMATION PUBLISHED THEREON) AND THE SERVICES ARE PROVIDED "AS IS" WITHOUT REPRESENTATION, WARRANTY OR CONDITION OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED REPRESENTATIONS, WARRANTIES OR CONDITIONS OF MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. LIFT DOES NOT REPRESENT OR WARRANT THAT THIS SITE OR THE SERVICES WILL MEET YOUR REQUIREMENTS OR THAT THEIR USE WILL BE UNINTERRUPTED OR ERROR-FREE. </p>
    <h4> 13. LIMITATION OF LIABILITY </h4>
    <p> LIFT DOES NOT PROVIDE MEDICAL ADVICE OR ANY OTHER SIMILAR SERVICE. WE DO NOT TAKE RESPONSIBILITY FOR ANY MEDICAL INFORMATION THAT MAY BE FOUND ON THE SITE OR SERVICES OR IN RELATION TO ANY PRODUCTS OR ACCESSORIES. </p>
    <p> ALL INFORMATION CONTAINED ON THE SITE IS FOR INFORMATIONAL PURPOSES ONLY AND IS NOT MEANT TO BE A SUBSTITUTE FOR THE ADVICE PROVIDED BY YOUR OWN DOCTOR OR OTHER HEALTH CARE PROVIDER. UNDER NO CIRCUMSTANCES SHOULD ANY SUCH INFORMATION BE USED FOR THE DIAGNOSIS OR TREATMENT OF ANY MEDICAL CONDITION. THE SITE IS NOT INTENDED TO REPLACE AN IN-PERSON VISIT TO YOUR DOCTOR. </p>
    <p> LIFT DOES NOT MANUFACTURE ANY PRODUCTS OR ACCESSORIES AVAILABLE FOR SALE ON THE SITE OR SERVICES. AS BETWEEN YOU AND LIFT, YOU ASSUME ALL RESPONSIBILITY AND RISK FOR USE OF THIS SITE AND THE SERVICES, INCLUDING WITHOUT LIMITATION ANY PRODUCTS OR ACCESSORIES PURCHASED THROUGH THE SITE OR SERVICES. IN PARTICULAR, AS BETWEEN YOU AND LIFT, YOU ASSUME ALL LIABILITY AND RISK FOR ANY INJURY WHATSOEVER, INCLUDING LOSS OF LIFE OR LOSS OF BODILY FUNCTION, SUSTAINED BY YOU IN CONNECTION WITH THE USAGE OF THE SITE AND THE SERVICES, INCLUDING WITHOUT LIMITATION THE USE OF ANY PRODUCTS OR ACCESSORIES PURCHASED THROUGH THE SITE OR SERVICES. YOU AGREE TO INDEMNIFY AND HOLD HARMLESS LIFT FROM ANY CLAIM RELATED TO THE FOREGOING. </p>
    <p> IN NO EVENT SHALL LIFT OR ANY OF ITS DIRECTORS, OFFICERS, EMPLOYEES, SHAREHOLDERS, PARTNERS, OR AGENTS BE LIABLE FOR ANY INCIDENTAL, INDIRECT, PUNITIVE, EXEMPLARY, CONSEQUENTIAL OR OTHER SIMILAR DAMAGES WHATSOEVER (OR FOR ANY DAMAGES FOR LOSS OF PROFITS, INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER PECUNIARY LOSS IN CONNECTION WITH ANY CLAIM, LOSS, DAMAGE, ACTION, SUIT OR OTHER PROCEEDING ARISING UNDER OR OUT OF THESE TERMS OF USE, INCLUDING WITHOUT LIMITATION YOUR USE OF, RELIANCE UPON, ACCESS TO, OR EXPLOITATION OF THIS SITE, THE SERVICES, OR ANY PART THEREOF, OR ANY RIGHTS GRANTED TO YOU HEREUNDER, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, WHETHER THE ACTION IS BASED ON CONTRACT, TORT (INCLUDING NEGLIGENCE), INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS OR OTHERWISE. </p>
    <p> IN EVERY EVENT, LIFT' TOTAL MAXIMUM AGGREGATE LIABILITY UNDER THESE TERMS OF USE OR THE USE OR EXPLOITATION OF ANY OR ALL PART OF THIS SITE AND/OR THE SERVICES IN ANY MANNER WHATSOEVER SHALL BE LIMITED TO THE LESSER OF ONE HUNDRED ($100.00) DOLLARS OR THE VALUE OF ANY PRODUCTS OR ACCESSORIES PURCHASED BY YOU THROUGH THE SITE OR SERVICES. </p>
    <p> SOME JURISDICTIONS DO NOT ALLOW FOR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. </p>
    <h4> 14. INDEMNIFICATION </h4>
    <p> YOU AGREE TO, UPON REQUEST, INDEMNIFY AND HOLD US HARMLESS FROM ANY AND ALL LIABILITIES, CLAIMS, LOSSES AND EXPENSES, INCLUDING ATTORNEYS' AND OTHER FEES AND COSTS, WHICH ARISE DIRECTLY OR INDIRECTLY FROM ANY BREACH OF THESE TERMS OF USE OR NEGLIGENCE FOR WHICH YOU ARE RESPONSIBLE. </p>
    <h4> 15. TERM &amp; TERMINATION </h4>
    <p> You acknowledge and agree that access to this Site and the Services may not be available from time to time, may be amended, revised, replaced, suspended or terminated in whole or in part at any time and without notice, and that Lift shall not, in any event, be responsible to you in any way should you be unable to access this Site and the Service at any time or from time to time. </p>
    <p> Lift may, at its sole discretion, at any time and from time to time, without notice, suspend your right to use this Site and the Services and/or terminate these Terms of Use (including any of the licenses granted hereunder). Without limiting the foregoing, these Terms of Use and the licenses granted herein shall automatically terminate, without notice, if you materially fail to perform or comply with these Terms of Use or any provision hereof. Upon termination of these Terms of Use, you shall immediately cease and desist from all use of this Site and the Services. </p>
    <p> Sections 12 - 19 will survive any termination or expiry of these Terms of Use. </p>
    <h4> 16. NOTICE </h4>
    <p> If you need to contact us regarding this Site, the Services or these Terms of Use, please e-mail us at support@lift.co. You can also contact us via mail addressed to: </p>
    <p> Lift Co. Ltd. </p>
    <p> 37 Bulwer Street </p>
    <p> Toronto ON </p>
    <p> M5T 1A1 </p>
    <h4> 17. YOUR COMMENTS </h4>
    <p> Feel free to email your comments, suggestions and feedback ("Comments") to Lift at the e-mail addresses provided in this Site or the Services. However, the Internet is not a fully secure medium and any communication may be lost, intercepted or altered. Lift is not liable for any damages related to communications to or from this Site or the Services. You agree with respect to any Comments provided by you to us, via e-mail or otherwise, that: (i) Lift has no obligation concerning such Comments; (ii) such Comments are non-confidential; (iii) Lift may use, disclose, distribute or copy such Comments and use any ideas, concepts or know-how contained in such Comments for any purpose and without restriction or obligation to you (or any third party); and (iv) such Comments are truthful, do not violate the legal rights of others, and are not the property of others. </p>
    <h4> 18. MISCELLANEOUS </h4>
    <p> These Terms of Use is governed by and construed in accordance with the laws of the Province of Ontario, Canada, without regards to its principles of conflicts of law. Subject to the obligation to arbitrate below, you agree to the exclusive personal jurisdiction of the courts located in Toronto, Ontario, Canada, and waive any jurisdictional, venue, or inconvenient forum objections to such courts. </p>
    <p> Except where prohibited by applicable law, any controversy, claim or dispute arising out of or relating to these Terms of Use, the Site or the Services or the relationship which results from these Terms of Use, including without limitation, the performance, breach, enforcement, existence or validity of the matters provided for in these Terms of Use or your receipt and use of the Site or Services, which cannot be amicably resolved, (collectively, a "Claim"), will be referred to and finally settled (to the exclusion of the courts) by private and confidential binding arbitration before a single arbitrator held in Toronto, Ontario in English and in accordance with the UNCITRAL Arbitration Rules, except as such rules are modified or waived herein. Although the appointing authority shall be a Justice of the Ontario Superior Court of Justice, the arbitrator will be a person who is legally trained and who has experience in the information technology field in Canada or the United States of America and is independent of either party. Any such Claim will be arbitrated on an individual basis, and will not be consolidated in any arbitration with any claim, controversy or dispute of any other party. Except where prohibited by applicable law, you agree to: (i) waive any right you may have to commence or participate in any class action against Lift relating to any Claim; (ii) opt out of any class proceedings against Lift; and (iii) waive, to the fullest extent permitted by law, any right of appeal. Notwithstanding the foregoing, Lift reserves the right to pursue the protection of intellectual property rights and confidential information through injunctive or other equitable relief through the courts. </p> <p> If any provision of these Terms of Use is found to be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from these Terms of Use and shall not affect the validity and enforceability of any remaining provisions. </p>
    <p> These Terms of Use (which incorporate by reference our Privacy Policy (https://lift.co/privacy) set out the entire agreement between us relating to the subject matter herein and supersede and any all prior or contemporaneous written or oral agreements between us. These Terms of Use are not assignable, transferable or sub-licensable by you except with Lift' prior written consent. No waiver by either party of any breach or default hereunder shall be deemed to be a waiver of any preceding or subsequent breach or default. Any heading, caption or section title contained in these Terms of Use is inserted only as a matter of convenience and in no way defines or explains any section or provision hereof. </p>
    <p> These Terms of Use were last updated on April 19, 2017. </p>
    <p> USE AT YOUR OWN RISK. </p>
  </div>`,
};

export default terms;
